#!/bin/bash

if [ $# -ge 1 ]; then
    REL_PATH="$1"

    # Check if the file exists
    if [ ! -f "${REL_PATH}" ]; then
        echo "Error: File ${REL_PATH} does not exist."
        exit 1
    fi

    # Call ROOT script with the relative path
    root --web=chrome -l "scripts/analyze_testbeam.C(\"${REL_PATH}\")"

else
    # root --web=chrome -l "scripts/replay_testbeam.C()"
    root -l "scripts/analyze_testbeam.C()"
fi
