#!/bin/bash

EXECUTABLE=motionControl
SCRIPT=motor_control.c

if [ -f $EXECUTABLE ]; then
    rm $EXECUTABLE
fi

gcc $(pkg-config --cflags gtk+-3.0) -o $EXECUTABLE motor_control.c $(pkg-config --libs gtk+-3.0)
